services:

  fastapi:
    build:
        context: .
        dockerfile: Dockerfile
    image: cc7261:fastapi
    container_name: fastapi
    ports:
      - 80:80
    volumes:
      - ./src:/app

  python:
    image: python:3.13.7-alpine3.21
    container_name: python
